version: '3'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    user: "$UID:$GID"
    command:
      - --config.file=/etc/prometheus/prometheus-conf.yml
      - --storage.tsdb.path=/prometheus
    volumes: 
      - ./prometheus-conf.yml:/etc/prometheus/prometheus-conf.yml:ro
      - ./prometheus_data:/prometheus
    depends_on:
      - cadvisor      

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
    - redis   
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana      
    depends_on: 
      - prometheus